export let datosbase = {
    codigo: '',
    cedula: '',
    nombre: '',
    ingreso: '',
    temporal: '',
    finca: '',
    salario: '',
    saldos: '',
    fondos: '',
    mercados: '',
    cuotasPrestamos: '',
    prestamoPaDescontar : '',
    cuotasCasino: '',
    casino: '',
    anchetas: '',
    cuotasfondo: '',
    fondo: '',
    carnet : '',
    seguroFunerario: '',
    prestamoPaHacer : '',
    cuotasAnticipoLiquidacion: '',
    anticipoLiquidacion: '',
    cuentas : '',
}