export let datosbase = {
    codigo: '',
    cedula: '',
    nombre: '',
    ingreso: '',
    temporal: '',
    finca: '',
    salario: '',
    saldos: '',
    fondos: '',
    mercados: '',
    cuotasMercados: '',
    prestamoPaDescontar : '',
    cuotasPrestamos: '',    
    casino: '',
    anchetas: '',
    cuotasAnchetas: '',
    fondo: '',
    carnet : '',
    seguroFunerario: '',
    prestamoPaHacer : '',
    cuotasPrestamoPahacer: '',
    anticipoLiquidacion: '',
    cuentas : '',
}

export let codigo = {
    codigo: '',
    uid : '',
    monto : '',
    cuotas : '',
    estado : true,
    lugar : 'Prestamo',
}