export let datosbase = {
    codigo: '',
    cedula: '',
    nombre: '',
    ingreso: '',
    temporal: '',
    finca: '',
    salario: '',
    saldos: '',
    fondos: '',
    mercados: '',
    cuotasMercados: '',
    prestamoPaDescontar : '',
    cuotasPrestamos: '',    
    casino: '',
    anchetas: '',
    cuotasAnchetas: '',
    fondo: '',
    carnet : '',
    seguroFunerario: '',
    prestamoPaHacer : '',
    cuotasPrestamoPahacer: '',
    anticipoLiquidacion: '',
    cuentas : '',
}

export let codigo = {
    codigo: '',    
    monto : '',
    cuotas : '',
    estado : true,
    lugar : 'Prestamo',
    cedulaQuienPide : '',
    jefeArea : '',
    coordinador : '',
    fechaGenerado : '',
    fechaEjecutado : '',
}

export let comercio = {
    codigo: '',
    concepto : '',
    destino : '',
    cantidadEnvio : '',
    cantidadRecibida : '',
    valorUnidad : '',
    cantidadTotalVendida : 0,
    PersonaEnvia : '',
    PersonaRecibe : '',
    fechaEnviada : '',
    fechaRecibida : '',     
}